### 1. Create type
POST localhost:8080/type/create
Content-Type: application/json

{
  "nameUz": "Ali",
  "nameRu": "Alish",
  "nameEn": "Valish",
  "orderNumber": 7
}

### 2. Update type
PUT localhost:8080/type/update/6
Content-Type: application/json

{
  "nameUz": "Fan-Texnika",
  "nameRu": "Технологии",
  "nameEn": "Tech",
  "orderNumber": 6
}

### 3. Delete type
DELETE localhost:8080/type/delete/70

### 4. Pagination
GET localhost:8080/type/pagination?page=2&size=4

### 5. Get All By language
GET localhost:8080/type/all?lang=ru

