### Attach upload
POST http://localhost:8081/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zari.jpg"

< /Users/akobir/Documents/zari.jpg

### load image
GET http://localhost:8081/attach/open/zari.jpg

###
POST http://localhost:8081/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zari.jpg"

< /Users/akobir/Documents/zari.jpg
