### Registration with phone
POST localhost:8081/auth/registrWithPhone
Content-Type: application/json

{
  "name": "Javohir",
  "surname": "Qodiriy",
  "phone": "998770031551",
  "password": "12345"
}

### Registration with email
POST localhost:8081/auth/registrWithEmail
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "akobirqodiriy@gmail.com",
  "password": "123456789"
}

### resend sms
GET localhost:8081/auth/registration/resendSms/998979213344

### resend email
GET localhost:8081/auth/registration/resendEmail/qodirovako1@gmail.com

### verification with phone
POST localhost:8081/auth/verificationWithSms
Content-Type: application/json

{
  "phone": "998979213344",
  "message": "Bu Eskiz dan test"
}


### login with email
POST localhost:8081/auth/loginWithEmail
Content-Type: application/json

{
  "email": "mazgi@gmail.com",
  "password": "12345"
}

### login with phone
POST localhost:8081/auth/loginWithPhone
Content-Type: application/json

{
  "phone": "998940460720",
  "password": "12345"
}

### login with email
POST localhost:8081/auth/login_email
Content-Type: application/json

{
  "email": "akobirqodiriy@gmail.com",
  "password": "123456789"
}
