### create profile
POST localhost:8081/profile/create
Content-Type: application/json

{
  "name": "Vali",
  "surname": "Valiyev",
  "email": "kunuz2@gmail.com",
  "phone": "998991233001",
  "password": "112244"
}

### get all with pagination
GET localhost:8081/profile/all_with_pagination?pageNumber=1&pageSize=11

### update for Admin
PUT localhost:8081/profile/update/1

### update for user
PUT localhost:8081/profile/current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTY5MTAyMzIsImlkIjo1Mywicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcxNjk5NjYzMiwianRpIjoiS3VuVXpUZXN0In0.MA5rRNxUS0-g29ju7GXNhOfJ_KQf0UJB2yxYPrOFvq8BaN8Ylv1a2-DYiPQGF6rre26Z1pcP128q31ccCRIrTg

{
  "name": "Alijons",
  "surname": "Valiyev"
}

### delete by id
DELETE localhost:8081/profile/delete/1

### filter profile
POST localhost:8081/profile/filter?pageNumber=1&pageSize=5
Content-Type: application/json

{
  "createdDateFrom": "2024-05-19T11:28",
  "createdDateTo": "2024-05-19T12:00"
}