### 1. Create type
POST localhost:8081/type/create
Content-Type: application/json

{
  "nameUz": "Ali",
  "nameRu": "Alish",
  "nameEn": "Valish",
  "orderNumber": 7
}

### 2. Update type
PUT localhost:8081/type/update/6
Content-Type: application/json

{
  "nameUz": "Fan-Texnika2",
  "nameRu": "Технологии2",
  "nameEn": "Tech2",
  "orderNumber": 7
}

### 3. Delete type
DELETE localhost:8081/type/delete/70

### 4. Pagination
GET localhost:8081/type/pagination?page=1&size=9

### 5. Get All By language
GET localhost:8081/type/lang
Accept-Language: EN

